name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    environment: qa

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      API_URL: ${{ secrets.API_URL }}
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      TEST_USER_1_ROLE: ${{ secrets.TEST_USER_1_ROLE }}
      TEST_USER_1_STATUS: ${{ secrets.TEST_USER_1_STATUS }}
      TEST_USER_1_USERNAME: ${{ secrets.TEST_USER_1_USERNAME }}
      TEST_USER_1_PASSWORD: ${{ secrets.TEST_USER_1_PASSWORD }}
      TEST_USER_2_ROLE: ${{ secrets.TEST_USER_2_ROLE }}
      TEST_USER_2_STATUS: ${{ secrets.TEST_USER_2_STATUS }}
      TEST_USER_2_USERNAME: ${{ secrets.TEST_USER_2_USERNAME }}
      TEST_USER_2_PASSWORD: ${{ secrets.TEST_USER_2_PASSWORD }}
      TEST_USER_3_ROLE: ${{ secrets.TEST_USER_3_ROLE }}
      TEST_USER_3_STATUS: ${{ secrets.TEST_USER_3_STATUS }}
      TEST_USER_3_USERNAME: ${{ secrets.TEST_USER_3_USERNAME }}
      TEST_USER_3_PASSWORD: ${{ secrets.TEST_USER_3_PASSWORD }}
      TEST_USER_4_ROLE: ${{ secrets.TEST_USER_4_ROLE }}
      TEST_USER_4_STATUS: ${{ secrets.TEST_USER_4_STATUS }}
      TEST_USER_4_USERNAME: ${{ secrets.TEST_USER_4_USERNAME }}
      TEST_USER_4_PASSWORD: ${{ secrets.TEST_USER_4_PASSWORD }}
      TEST_USER_5_ROLE: ${{ secrets.TEST_USER_5_ROLE }}
      TEST_USER_5_STATUS: ${{ secrets.TEST_USER_5_STATUS }}
      TEST_USER_5_USERNAME: ${{ secrets.TEST_USER_5_USERNAME }}
      TEST_USER_5_PASSWORD: ${{ secrets.TEST_USER_5_PASSWORD }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
